proxy-groups:
  - {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [{providers_tags}], include-all-providers: true}
  - {name: ğŸªŸ å¾®è½¯æœåŠ¡, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸŒ å›½å¤–åª’ä½“, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, {providers_tags}, ğŸ¯ å…¨çƒç›´è¿]}
  - {name: ğŸŸ¢ å…¨çƒç»•è¿‡, type: select, proxies: [PASS], hidden: true}
  - {name: ğŸ¯ å…¨çƒç›´è¿, type: select, proxies: [DIRECT], hidden: true}
rule-providers:

rules:
  - GEOIP,cn,ğŸ¯ å…¨çƒç›´è¿
  - GEOSITE,microsoft-cn,ğŸªŸ å¾®è½¯æœåŠ¡
  - GEOSITE,media,ğŸŒ å›½å¤–åª’ä½“
  - GEOIP,telegram,ğŸ“² ç”µæŠ¥æ¶ˆæ¯,no-resolve
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
