
proxy-groups:
  - {name:  èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [{providers_tags}], include-all-providers: true}
  - {name:  ğŸªŸ å¾®è½¯æœåŠ¡, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿,  èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿,  èŠ‚ç‚¹é€‰æ‹©]}
  - {name:  è‹¹æœæœåŠ¡, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿,  ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name:  ğŸŒ å›½å¤–åª’ä½“, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿,  ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name:  ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, {providers_tags},  å…¨çƒç›´è¿]}
  - {name:  ğŸŸ¢ å…¨çƒç»•è¿‡, type: select, proxies: [PASS], hidden: true}
  - {name:  ğŸ¯ å…¨çƒç›´è¿, type: select, proxies: [DIRECT], hidden: true}

rule-providers:
  AI:
    type: http
    behavior: classical
    format: yaml
    path: './rules/AI.yaml'
    url: 'https://raw.githubusercontent.com/zeevyan/clash-rule/refs/heads/main/AI.yaml'
    interval: 86400

  Emby:
    type: http
    behavior: classical
    format: yaml
    path: './rules/Emby.yaml'
    url: 'https://raw.githubusercontent.com/zeevyan/clash-rule/refs/heads/main/Emby.yaml'
    interval: 86400

  Proxymedia:
    type: http
    behavior: classical
    format: yaml
    path: './rules/Proxymedia.yaml'
    url: 'https://raw.githubusercontent.com/zeevyan/clash-rule/refs/heads/main/Proxymedia.yaml'
    interval: 86400

  telegramip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./rules/telegramip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/telegramip.mrs"
    interval: 86400

  mediaip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./rules/mediaip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/mediaip.mrs"
    interval: 86400

rules:
  - GEOIP,cn,ğŸ¯ å…¨çƒç›´è¿
  - GEOSITE,microsoft-cn,ğŸªŸ å¾®è½¯æœåŠ¡
  - RULE-SET,apple-cn,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,Proxymedia,ğŸŒ å›½å¤–åª’ä½“
  - GEOSITE,media,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,mediaip,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - GEOIP,telegram,ğŸ“² ç”µæŠ¥æ¶ˆæ¯,no-resolve
  - RULE-SET,telegramip,ğŸ“² ç”µæŠ¥æ¶ˆæ¯,no-resolve
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
