
proxy-groups:
  - {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [{providers_tags}], include-all-providers: true, direct}
  - {name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, {providers_tags}], include-all-providers: true}
  - {name: ğŸ è‹¹æœæœåŠ¡, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, {providers_tags}], include-all-providers: true}
  - {name: ğŸŒ å›½å¤–åª’ä½“, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, {providers_tags}], include-all-providers: true}
  - {name: ğŸŒ Emby, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, {providers_tags}], include-all-providers: true}
  - {name: ğŸ‘‘ å¾®åš, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, {providers_tags}], include-all-providers: true}
  - {name: ğŸ”’ IP, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, {providers_tags}], include-all-providers: true}
  - {name: ğŸ¤– äººå·¥æ™ºèƒ½, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, {providers_tags}], include-all-providers: true}
  - {name: ğŸ¥ XPTV, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, {providers_tags}], include-all-providers: true}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ¯ å…¨çƒç›´è¿, type: select, proxies: [DIRECT], hidden: true}

rule-providers:
  AI:
    type: http
    behavior: classical
    format: yaml
    path: './rules/AI.yaml'
    url: 'https://raw.githubusercontent.com/zeevyan/clash-rule/refs/heads/main/AI.yaml'
    interval: 86400

  apple-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./rules/apple-cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/apple-cn.mrs"
    interval: 86400


  Emby:
    type: http
    behavior: classical
    format: yaml
    path: './rules/Emby.yaml'
    url: 'https://raw.githubusercontent.com/zeevyan/clash-rule/refs/heads/main/Emby.yaml'
    interval: 86400

  Proxymedia:
    type: http
    behavior: classical
    format: yaml
    path: './rules/Proxymedia.yaml'
    url: 'https://raw.githubusercontent.com/zeevyan/clash-rule/refs/heads/main/Proxymedia.yaml'
    interval: 86400

  telegramip:
    type: http
    behavior: classical
    format: yaml
    path: ./rules/telegramip.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram_No_Resolve.yaml"
    interval: 86400


  cnip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./rules/cnip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cnip.mrs"
    interval: 86400

  weibo:
    type: http
    behavior: classical
    format: yaml
    path: './rules/weibo.yaml'
    url: 'https://raw.githubusercontent.com/zeevyan/clash-rule/refs/heads/main/weibo.yaml'
    interval: 86400
  ip:
    type: http
    behavior: classical
    format: yaml
    path: './rules/ip.yaml'
    url: 'https://raw.githubusercontent.com/zeevyan/clash-rule/refs/heads/main/ip.yaml'
    interval: 86400
  xptv:
    type: http
    behavior: classical
    format: yaml
    path: './rules/xptv.yaml'
    url: 'https://raw.githubusercontent.com/zeevyan/clash-rule/refs/heads/main/xptv.yaml'
    interval: 86400


rules:

  - RULE-SET,apple-cn,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,Proxymedia,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,AI,ğŸ¤– äººå·¥æ™ºèƒ½
  - RULE-SET,weibo,ğŸ‘‘ å¾®åš
  - RULE-SET,ip,ğŸ”’ IP,no-resolve
  - RULE-SET,Emby,ğŸŒ Emby
  - RULE-SET,xptv,ğŸ¥ XPTV
  - RULE-SET,telegramip,ğŸ“² ç”µæŠ¥æ¶ˆæ¯
  - GEOSITE,category-games@cn,ğŸ¯ å…¨çƒç›´è¿
  - DOMAIN-SUFFIX,steamserver.net,ğŸ¯ å…¨çƒç›´è¿
  - DOMAIN-SUFFIX,cm.steampowered.com,ğŸ¯ å…¨çƒç›´è¿
  - GEOSITE,CN,ğŸ¯ å…¨çƒç›´è¿
  - GEOSITE,geolocation-!cn,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,cnip,ğŸ¯ å…¨çƒç›´è¿,no-resolve
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
